# Implementasi K-NN

Algoritma KNN, bekerja berdasarkan jarak terpendek dari query instance ke sampel data latih untuk menentukan KNN. <br> <br>
Metode pencarian jarak yang digunakan adalah **Euclidean Distance** yaitu perhitungan jarak terdekat.
> Formula
<br> 
$$
\begin{aligned}
d(\mathbf{p}, \mathbf{q})=d(\mathbf{q}, \mathbf{p}) &=\sqrt{\left(q_1-p_1\right)^2+\left(q_2-p_2\right)^2+\cdots+\left(q_n-p_n\right)^2} \\
&=\sqrt{\sum_{i=1}^n\left(q_i-p_i\right)^2}
\end{aligned}
$$
<br>

Dengan:<br>
$d_{(i, f)}:$ Jarak dokumen ke-i ke dokumen ke-j <br>
$x_{i(n)}$ : Kata ke $n$ di dokumen ke- $i$ <br>
$x_{j(n)}:$ Kata ke $n$ di dokumen ke- $j$ <br>

In [ ]:
import pandas as pd

In [ ]:
url="https://raw.githubusercontent.com/diahkamalia/DataMining1/main/IRIS.csv"
df = pd.read_csv(url)
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [56]:
X = df.iloc[:, :-1]
y = df.loc[:, "species"]
y = df['species'].values

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [59]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

In [60]:
classes={'Iris-setosa':'Setosa','Iris-versicolor':'Versicolor','Iris-virginica':'Virginica'}
X_new = [[6.0,	3.7, 6.2,	2.3]]
y_predict = knn.predict(X_new)
print(classes[y_predict[0]])

Virginica